### Site metadata

title: "nummy's art"
description: "nummy's art"

url: "https://nummy.pics"
baseurl: ""

github_username: "lynkray"
repository: "lynkray/art"

google_analytics_key: ""

# For SEO tag.
logo: /siteicon.png
author:
  name: nummy
  twitter:
social:
  name: nummy
  links:
    - https://nummy.pics

### Build settings

timezone: Etc/UTC

permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      text_width: true
  - scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
  - LICENCE-source
  - Makefile
  - netlify.toml
